# Site settings
baseurl: '/'
title: "BluGuard: We safeguard your digital space, allowing you to focus on what matters most"
url: "http://thebluguard.com"
github_username: blusafe
logo: "assets/logo.png"

# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter_opts:
    default_lang: xml

header_pages:
  - get_started.md
  - url: /docs/
    title: Documentation
  - forums.md
  - url: /examples/
    title: Examples
  - showcases.md
  - integrations.md

sass:
  style: compressed

plugins:
  - jekyll-environment-variables

logo:
  mobile: "images/logo/logo-mobile.jpg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.jpg"
  desktop_height: "65px"
  desktop_width: "65px"


collections:
  showcases:
    output: true
  examples:
    output: true
    permalink: /examples/:name/index.html


defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: "team"
      type: "team"
    values:
      layout: "team"

exclude:
  - .editorconfig
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-environment-variables
