# Site settings
title: "BluGuard: We safeguard your digital space, allowing you to focus on what matters most"
url: "http://thebluguard.com"
github_username: blusafe

# Build settings
markdown: kramdown
